---
title: "Data tidying"
author: "Nelson Crockett"
date: "October 16, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=F, message=F}
library(dplyr)
library(tidyr)
```

```{r}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method="libcurl"), stringsAsFactors=FALSE)
head(catch_df)
```

selecting columns for analysis
```{r}
catch_clean <- catch_df %>% 
  select(-All, -notesRegCode) %>% 
  gather(key = "species", value = "catch", -Region, -Year) %>% 
  #spread(key = "Region", value = "catch")
  rename(catch_thousands = catch)


tail(catch_clean)
```

Transforming chr to int

```{r}
test <- as.numeric(catch_clean$catch_thousands)
i <- which(is.na(test) == T)
print(i)
catch_clean[i, ]

```


fixing typo
Adding columns
dropping column

```{r}
catch_clean_mutated <- catch_clean %>%
  mutate(catch_thousands = ifelse(catch_thousands == "I" , 1, catch_thousands)) %>% 
  mutate(catch_thousands = as.numeric(catch_thousands)) %>% 
  mutate(catch = catch_thousands * 1000) %>% 
  select(-catch_thousands)

tail(catch_clean_mutated)
```

spliting using groupby

```{r}
catch_summarized <- catch_clean_mutated %>% 
  group_by(Region, Year) %>% 
  summarize(mean_catch = mean(catch), n_obs = n())

head(catch_summarized)
```


```{r}
catch_chinook <- catch_clean_mutated %>% 
  filter(species == "Chinook") %>% 
  arrange(-catch)

head(catch_chinook)
```


```{r}
region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl"),stringsAsFactors = FALSE)

head(region_defs)
```

```{r}
region_defs <- region_defs %>% 
  select(code, mgmtArea)

head(region_defs)
```



```{r}
catch_joined <- left_join(catch_clean_mutated, region_defs, by = c("Region" = "code"))

head(catch_joined)

i <- which(is.na(catch_joined$mgmtArea))
nrow(i)
```

```{r}
dates_df <- data.frame(date = c("5/24/1930",
                                "5/25/1930",
                                "5/26/1930",
                                "5/27/1930",
                                "5/28/1930"),
                       stringsAsFactors = FALSE)

```


```{r}
dates_separate <- dates_df %>% 
  separate(date, into = c("month", "day", "year"), "/", remove=F) %>% 
  unite(col = date_iso, year, month, day, sep = "-")

dates_separate
```






